export const API_ROUTES = {
  auth: {
    authenticate: '/auth/authenticate',
    passwordResetRequest: '/auth/password-reset/request',
    passwordResetValidate: '/auth/password-reset/validate/{token}',
    passwordResetConfirm: '/auth/password-reset/confirm',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    revoke: '/auth/revoke',
  },
  artists: {
    list: '/artists',
    recent: '/artists/recent',
    detail: '/artists/{id}',
    albums: '/artists/{id}/albums',
    songs: '/artists/{id}/songs',
    starred: '/artists/starred/{apiKey}/{isStarred}',
    hated: '/artists/hated/{apiKey}/{isHated}',
    setRating: '/artists/setrating/{apiKey}/{rating}',
    user: '/user/artists/{category}',
  },
  albums: {
    list: '/albums',
    recent: '/albums/recent',
    detail: '/albums/{id}',
    songs: '/albums/{id}/songs',
    starred: '/albums/starred/{apiKey}/{isStarred}',
    hated: '/albums/hated/{apiKey}/{isHated}',
    setRating: '/albums/setrating/{apiKey}/{rating}',
    genres: '/genres',
    genreSongs: '/genres/{genreId}/songs',
  },
  songs: {
    list: '/songs',
    random: '/songs/random',
    detail: '/songs/{id}',
    starred: '/songs/starred/{apiKey}/{isStarred}',
    hated: '/songs/hated/{apiKey}/{isHated}',
    setRating: '/songs/setrating/{apiKey}/{rating}',
    lyrics: '/songs/{id}/lyrics',
    stream: '/song/stream/{apiKey}/{userApiKey}/{authToken}',
  },
  playlists: {
    list: '/playlists',
    detail: '/playlists/{apiKey}',
    create: '/playlists',
    songs: '/playlists/{apiKey}/songs',
    image: '/playlists/{apiKey}/image',
    reorder: '/playlists/{apiKey}/songs/reorder',
    smartList: '/playlists/smart',
    smartDetail: '/playlists/smart/{id}',
  },
  system: {
    info: '/system/info',
    stats: '/system/stats',
  },
  search: {
    basic: '/search',
    songs: '/search/songs',
    advanced: '/search/advanced',
    similar: '/search/similar/{id}/{type}',
    suggest: '/search/suggest',
  },
  shares: {
    list: '/shares',
    detail: '/shares/{apiKey}',
    public: '/shares/public/{shareUniqueId}',
  },
  themes: {
    list: '/themes',
    apply: '/themes/me',
    import: '/themes/import',
    export: '/themes/{themeId}/export',
    file: '/themes/{themeId}/file/{fileName}',
    rescan: '/themes/rescan',
    remove: '/themes/{themeId}',
  },
  equalizer: {
    presets: '/equalizer/presets',
    removePreset: '/equalizer/presets/{id}',
  },
  analytics: {
    listening: '/analytics/listening',
    top: '/analytics/top/{period}',
  },
  user: {
    me: '/user/me',
    stats: '/user/stats',
    statsHistory: '/user/stats/history',
    statsPlaysPerDay: '/user/stats/plays-per-day',
    statsTopGenres: '/user/stats/top-genres',
    statsTopSongs: '/user/stats/top-songs',
    liked: '/user/{entity}/liked',
    disliked: '/user/{entity}/disliked',
    topRated: '/user/{entity}/top-rated',
    rated: '/user/{entity}/rated',
    recentlyPlayed: '/user/{entity}/recently-played',
    lastPlayed: '/user/last-played',
    songs: '/user/songs/{filter}',
    albums: '/user/albums/{filter}',
    artists: '/user/artists/{filter}',
  },
  scrobble: {
    create: '/scrobble',
    lastfmAuthUrl: '/scrobble/lastfm/auth-url',
    lastfmSession: '/scrobble/lastfm/session',
    lastfmDisconnect: '/scrobble/lastfm/disconnect',
  },
  audio: {
    bpm: '/audio/bpm',
    features: '/audio/features/{id}',
  },
  requests: {
    list: '/requests',
    detail: '/requests/{apiKey}',
    comments: '/requests/{requestApiKey}/comments',
    seen: '/requests/{requestApiKey}/seen',
    complete: '/requests/{requestApiKey}/complete',
    activity: '/requests/activity',
    unreadActivity: '/requests/activity/unread',
  },
  playback: {
    status: '/playback-backend/status',
    settings: '/playback/settings',
    backends: '/playback-backend/capabilities',
    registerBackend: '/playback-backend/register-endpoint',
    initializeBackend: '/playback-backend/initialize',
    shutdownBackend: '/playback-backend/shutdown',
    heartbeat: '/playback-backend/heartbeat/{sessionId}',
    endpoints: '/endpoints',
    endpointForSession: '/endpoints/for-session/{sessionId}',
    endpointAttach: '/endpoints/{endpointId}/attach',
    endpointDetach: '/endpoints/{endpointId}/detach',
  },
  admin: {
    users: '/admin/users',
  },
  charts: {
    list: '/charts',
    detail: '/charts/{idOrSlug}',
    asPlaylist: '/charts/{idOrSlug}/playlist',
  },
  artistLookup: {
    search: '/artist-lookup',
    providers: '/artist-lookup/providers',
  },
  podcasts: {
    list: '/rest/getPodcasts',
    newest: '/rest/getNewestPodcasts',
    refresh: '/rest/refreshPodcasts',
    createChannel: '/rest/createPodcastChannel',
    deleteChannel: '/rest/deletePodcastChannel',
    deleteEpisode: '/rest/deletePodcastEpisode',
    downloadEpisode: '/rest/downloadPodcastEpisode',
    streamEpisode: '/rest/streamPodcastEpisode',
  },
} as const;

export type ApiRouteMap = typeof API_ROUTES;
